package logic;

public class UserInterface extends javax.swing.JFrame {

    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PremiseTextField = new javax.swing.JTextField();
        ConclusionTextField = new javax.swing.JTextField();
        PButton = new javax.swing.JButton();
        QButton = new javax.swing.JButton();
        RButton = new javax.swing.JButton();
        OpenButton = new javax.swing.JButton();
        AndButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        OrButton = new javax.swing.JButton();
        ImplyButton = new javax.swing.JButton();
        ButButton = new javax.swing.JButton();
        premiseLabel = new javax.swing.JLabel();
        conclusionLabel = new javax.swing.JLabel();
        AnswerButton = new javax.swing.JButton();
        CommaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PremiseTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PremiseTextFieldMouseClicked(evt);
            }
        });

        ConclusionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConclusionTextFieldMouseClicked(evt);
            }
        });

        PButton.setText("p");
        PButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PButtonMouseClicked(evt);
            }
        });

        QButton.setText("q");
        QButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QButtonMouseClicked(evt);
            }
        });

        RButton.setText("r");
        RButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RButtonMouseClicked(evt);
            }
        });

        OpenButton.setText("(");
        OpenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenButtonMouseClicked(evt);
            }
        });

        AndButton.setText("&");
        AndButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AndButtonMouseClicked(evt);
            }
        });

        CloseButton.setText(")");
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });

        OrButton.setText("v");
        OrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrButtonMouseClicked(evt);
            }
        });

        ImplyButton.setText("→");
        ImplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImplyButtonMouseClicked(evt);
            }
        });

        ButButton.setText("⊥");
        ButButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButButtonMouseClicked(evt);
            }
        });

        premiseLabel.setText("Premise");

        conclusionLabel.setText("Conclusion");

        AnswerButton.setText("Answer");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });

        CommaButton.setText(",");
        CommaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommaButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OrButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(QButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImplyButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnswerButton)
                            .addComponent(CommaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(premiseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conclusionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PremiseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(ConclusionTextField))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PremiseTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conclusionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConclusionTextField))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PButton)
                            .addComponent(RButton)
                            .addComponent(QButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OpenButton)
                            .addComponent(AndButton)
                            .addComponent(CloseButton)))
                    .addComponent(AnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImplyButton)
                    .addComponent(OrButton)
                    .addComponent(ButButton)
                    .addComponent(CommaButton))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String focusOn = "premise";
    public static String[] formula;
    public static boolean[] value;
    public static Creater c;

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        String premise = PremiseTextField.getText();
        String conclusion = ConclusionTextField.getText();
        CheckValidity cv = new CheckValidity(premise, conclusion);
        if (cv.isValid()) {
            c = new Creater(premise, conclusion);
            c.createTree();
            DrawTreeFour dt = new DrawTreeFour();
            dt.setVisible(true);
        } else {
            formula = cv.getFormul();
            value = cv.getValue();
            Unsatisfiable u = new Unsatisfiable();
            u.setVisible(true);
        }
    }//GEN-LAST:event_AnswerButtonActionPerformed

    private void PremiseTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PremiseTextFieldMouseClicked
        focusOn = "premise";
    }//GEN-LAST:event_PremiseTextFieldMouseClicked

    private void ConclusionTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConclusionTextFieldMouseClicked
        focusOn = "conclusion";
    }//GEN-LAST:event_ConclusionTextFieldMouseClicked

    private void PButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "p";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "p";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_PButtonMouseClicked

    private void QButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "q";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "q";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_QButtonMouseClicked

    private void RButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "r";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "r";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_RButtonMouseClicked

    private void OpenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "(";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "(";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_OpenButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + ")";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + ")";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void AndButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AndButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "&";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "&";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_AndButtonMouseClicked

    private void OrButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "v";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "v";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_OrButtonMouseClicked

    private void ButButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "⊥";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "⊥";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_ButButtonMouseClicked

    private void ImplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImplyButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + "→";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + "→";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_ImplyButtonMouseClicked

    private void CommaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommaButtonMouseClicked
        if (focusOn.equals("premise")) {
            String text = PremiseTextField.getText();
            text = text + ",";
            PremiseTextField.setText(text);
        } else {
            String text = ConclusionTextField.getText();
            text = text + ",";
            ConclusionTextField.setText(text);
        }
    }//GEN-LAST:event_CommaButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndButton;
    private javax.swing.JButton AnswerButton;
    private javax.swing.JButton ButButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton CommaButton;
    private javax.swing.JTextField ConclusionTextField;
    private javax.swing.JButton ImplyButton;
    private javax.swing.JButton OpenButton;
    private javax.swing.JButton OrButton;
    private javax.swing.JButton PButton;
    private javax.swing.JTextField PremiseTextField;
    private javax.swing.JButton QButton;
    private javax.swing.JButton RButton;
    private javax.swing.JLabel conclusionLabel;
    private javax.swing.JLabel premiseLabel;
    // End of variables declaration//GEN-END:variables
}
